# Include to create a share section in smb.conf and the share path directory.
# 
# Requires `_samba_share` variable to be defined as
# 
#     {
#       name: string,       # Name of share (config section name)
#       path: string,       # Path to directory
#       path_owner: string, # User to set as directory owner
#       [key]: any,         # Option name/value pairs to add to section
#     }
# 

- name: >-
    Remove share section [{{ _samba_share.name }}] in Samba conf
  ini_file:
    path: /etc/samba/smb.conf
    section: "{{ _samba_share.name }}"
    state: absent

- name: >-
    Add share section [{{ _samba_share.name }}] to Samba conf
  with_dict: "{{ _samba_share }}"
  when: >-
    item.key not in ['name', 'path_owner'] and
    item.value is not none and
    item.value != ''
  ini_file:
    path: /etc/samba/smb.conf
    section: "{{ _samba_share.name }}"
    option: "{{ item.key }}"
    value: "{{ item.value | ini_enc_value }}"
  notify: samba_restart

- name: >-
    Create share {{ _samba_share.name }} directory at {{ _samba_share.path }}
    and set ownership to {{ _samba_share.path_owner }}::sambashare
  file:
    path: "{{ _samba_share.path }}"
    state: directory
    owner: "{{ _samba_share.path_owner }}"
    group: sambashare
