# https://linuxize.com/post/how-to-install-and-configure-samba-on-ubuntu-18-04/

- name: Install Samba
  apt:
    pkg: samba
  
- name: Allow Samba through UFW
  # loop: "{{ samba_allow_from_ips }}"
  ufw:
    rule: allow
    name: Samba
    # from_ip: "{{ item }}"

- name: Copy smb.conf
  when: samba_config_src is not none
  copy:
    src: "{{ samba_config_src }}"
    dest: /etc/samba/smb.conf
  notify: samba_restart
    
- name: Create Samba users
  loop: "{{ samba_users }}"
  user:
    name: "{{ item.name }}"
    shell: /usr/sbin/nologin
    group: sambashare
    create_home: "{{ item.get('create_home', True) }}"

- name: Add shares to smb.conf
  loop: "{{ samba_shares }}"
  loop_control:
    loop_var: _samba_share
  include_tasks: "{{ role_path }}/tasks/_share.yaml"
