# https://www.liquidweb.com/kb/how-to-install-pyenv-on-ubuntu-18-04/
# https://github.com/pyenv/pyenv#basic-github-checkout

- name: Install pyenv deps with apt
  apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
    pkg:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - python-openssl
      - git

- name: >-
    Clone pyenv git repo to ~/.pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv_root }}"
    update: "{{ pyenv_update }}"
    depth: 1

- name: >-
    Add env var exports to ~/.bashrc
  blockinfile:
    dest: "{{ ansible_facts.env.HOME }}/.bashrc"
    block: |
      # pyenv config
      export PYENV_ROOT="{{ pyenv_root }}"
      export PATH="$PYENV_ROOT/bin:$PATH"
    marker: '# {mark} ANSIBLE MANAGED'
    