# See https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh
# 
# Var names kept the same with `gitlab_` prefix to make it easier...
# 

gitlab_gpg_key_url: https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey

gitlab_apt_source_path: /etc/apt/sources.list.d/gitlab_gitlab-ee.list

# https://packages.gitlab.com/docs#os_distro_version
gitlab_apt_config_url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/config_file.list?os={{ ansible_facts['distribution'] }}&dist={{ ansible_facts['distribution_release'] }}&source=script"

gitlab_config_src: null

gitlab_config_dest: /etc/gitlab/gitlab.rb
