humans_admin_group: admin
humans_group: humans

humans_admins: "{{ humans | selectattr('admin', 'true') | list }}"
humans_users: "{{ humans | selectattr('admin', 'false') | list }}"

humans_auth_admins_as_users: false
humans_authorized_key_exclusive: "{{ not humans_auth_admins_as_users }}"

humans_git: yes

# Paths
# ============================================================================
# 
# Trying to consolidate all paths here as they *may* need to be switched via
# the specific Linux distro at some future point (all the tasks seems generic).
# 

humans_sudoers_path: /etc/sudoers
humans_sshd_config_path: /etc/ssh/sshd_config
