openssl_sscrt_name: "{{ openssl_sscrt_common_name }}"

openssl_sscrt_crt_dest: "{{ openssl_sscrt_dest }}/{{ openssl_sscrt_name }}.crt"
openssl_sscrt_key_dest: "{{ openssl_sscrt_dest }}/{{ openssl_sscrt_name }}.key" 
openssl_sscrt_config_path: "{{ openssl_sscrt_dest }}/{{ openssl_sscrt_name }}.conf"

openssl_sscrt_default_bits: 4096
openssl_sscrt_default_md: sha512
openssl_sscrt_default_keyfile: "{{ openssl_sscrt_key_dest }}"
openssl_sscrt_prompt: false
openssl_sscrt_encrypt_key: false

openssl_sscrt_country_name: CN
openssl_sscrt_state_or_province_name: Fujian
openssl_sscrt_locality_name: Xiamen
openssl_sscrt_postal_code: null
openssl_sscrt_street_address: null
openssl_sscrt_organization_name: null
openssl_sscrt_organization_unit_name: null
openssl_sscrt_email_address: "webmaster@{{ openssl_sscrt_common_name }}"

openssl_sscrt_domains: "{{ openssl_sscrt_common_name }}"

openssl_sscrt_days: 3650 # ~10 years
openssl_sscrt_newkey: rsa:4096
