namespace: nansi
name: erlang
version: 0.1.0
readme: README.md
authors:
  - NR$ER (https://github.com/nrser)
description: null
license_file: LICENSE
tags: []
dependencies:
  community.general: '>=1.3.1'
repository: https://github.com/nrser/nansi.collections
documentation: https://github.com/nrser/nansi.collections
homepage: https://github.com/nrser/nansi.collections
issues: https://github.com/nrser/nansi.collections/issues
