# Need `apt_cache_valid_time`
- include_role:
    name: nrser/ubuntu

- name: Install iperf3
  apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
    pkg:
      - iperf3

- name: Install iperf3.service
  copy:
    src: iperf3.service
    dest: /etc/systemd/system/iperf3.service

- name: >-
    Open the port
    {{ iperf3_allow_from_ip }} -> {{ iperf3_allow_to_ip }}:{{ iperf3_port }}
  # Like `ufw allow from 10.0.1.0/16 to 10.0.1.8 port 5201`
  ufw:
    rule: allow
    from_ip: "{{ iperf3_allow_from_ip }}"
    to_ip: "{{ iperf3_allow_to_ip }}"
    to_port: "{{ iperf3_port }}"

- name: Start iperf3.service
  service:
    name: iperf3
    state: started
