apt_cache_valid_time: 86400

pg_version: 13

pg_client: true
pg_contrib: true
pg_frontend_dev: false
pg_backend_dev: false

pg_service_name: postgresql
pg_service_enabled: true
pg_service_state: started

pg_local_admin_users: null

pg_os_conf_dir:
  family:
    debian: "/etc/postgresql/{{ pg_version }}/main"
    # (Homebrew)
    darwin: /usr/local/var/postgres
    
pg_conf_dir: "{{ lookup('os_dig', pg_os_conf_dir) }}"

pg_indent_conf_path: "{{ (pg_conf_dir, 'pg_ident.conf') | nansi.util.to_path }}"
pg_hba_conf_path: "{{ (pg_conf_dir, 'pg_hba.conf') | nansi.util.to_path }}"
