- name: Copy files/bin contents
  loop: >-
    {{ lookup(
      'fileglob',
      (role_path, 'files', 'bin', "_.*") | nansi.util.to_path,
      wantlist=True
    ) }}
  copy:
    src: "{{ item }}"
    dest: "{{ (opscripts_bin_dest, item | basename) | nansi.util.to_path }}"
    mode: '0755'
