# https://apfelboymchen.net/gnu/notes/openssl%20multidomain%20with%20config%20files.html
# https://web.archive.org/web/20170323225247/http://firefly.iteye.com/blog/177547

- name: Create dest directory
  file:
    path: "{{ openssl_sscrt_dest }}"
    state: directory

- name: Delete any previous config file
  file:
    path: "{{ openssl_sscrt_config_path }}"
    state: absent

- name: Write [req] section of config file
  with_dict:
    default_bits: "{{ openssl_sscrt_default_bits }}"
    default_md: "{{ openssl_sscrt_default_md }}"
    default_keyfile: "{{ openssl_sscrt_default_keyfile }}"
    prompt: "{{ openssl_sscrt_prompt }}"
    encrypt_key: "{{ openssl_sscrt_encrypt_key }}"
    distinguished_name: req_distinguished_name
    req_extensions: v3_req
  when: item.value is not none and item.value != ''
  ini_file:
    path: "{{ openssl_sscrt_config_path }}"
    section: req
    option: "{{ item.key }}"
    value: "{{ item.value | openssl_sscrt_enc_value }}"
  

- name: Write [req_distinguished_name] section of config file
  with_dict:
    countryName: "{{ openssl_sscrt_country_name }}"
    stateOrProvinceName: "{{ openssl_sscrt_state_or_province_name }}"
    localityName: "{{ openssl_sscrt_locality_name }}"
    postalCode: "{{ openssl_sscrt_postal_code }}"
    streetAddress: "{{ openssl_sscrt_street_address }}"
    organizationName: "{{ openssl_sscrt_organization_name }}"
    organizationalUnitName: "{{ openssl_sscrt_organization_unit_name }}"
    commonName: "{{ openssl_sscrt_common_name }}"
    emailAddress: "{{ openssl_sscrt_email_address }}"
  when: item.value is not none and item.value != ''
  ini_file:
    path: "{{ openssl_sscrt_config_path }}"
    section: req_distinguished_name
    option: "{{ item.key }}"
    value: "{{ item.value | openssl_sscrt_enc_value }}"

- name: Write [v3_req] section of config file
  with_dict:
    subjectAltName: "{{ openssl_sscrt_domains | openssl_sscrt_fmt_domains }}"
  when: item.value is not none and item.value != ''
  ini_file:
    path: "{{ openssl_sscrt_config_path }}"
    section: v3_req
    option: "{{ item.key }}"
    value: "{{ item.value | openssl_sscrt_enc_value }}"

- name: Generate certificate
  command:
    argv:
      - /usr/bin/openssl
      - req
      - -x509
      - -days
      - "{{ openssl_sscrt_days }}"
      - -newkey
      - "{{ openssl_sscrt_newkey }}"
      - -config
      - "{{ openssl_sscrt_config_path }}"
      - -keyout
      - "{{ openssl_sscrt_key_dest }}"
      - -out
      - "{{ openssl_sscrt_crt_dest }}"
