---
# https://docs.ansible.com/ansible/latest/modules/user_module.html
# https://docs.ansible.com/ansible/latest/modules/authorized_key_module.html
# 

- name: Create 'wheel' group
  group:
    name: wheel
    state: present
    
- name: Allow 'wheel' group to have password-less sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  
- with_items: "{{ admin_users }}"
  name: Create admin users
  user:
    name: "{{ item['name'] }}"
    state: present
    create_home: true
    shell: /bin/bash

- with_items: "{{ admin_users }}"
  name: Add admin users to wheel group
  user:
    name: "{{ item.name }}"
    groups: wheel
    append: true
  # command: "usermod -aG wheel {{ item.name }}"
  
- with_items: "{{ admin_users }}"
  name: Set the admin_users users' ssh keys from their ones on github
  authorized_key:
    user: "{{ item['name'] }}"
    key: "https://github.com/{{ item['github'] }}.keys"
    exclusive: true

# it's much more secure to use ssh keys
- name: Disallow SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^\\#?PasswordAuthentication"
    line: PasswordAuthentication no
    state: present
  notify: restart ssh

# turning off root ssh access is a security best practice
- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: PermitRootLogin no
    state: present
  notify: restart ssh

- name: ONLY allow login for the admin users
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^\\#?AllowUsers"
    line: "AllowUsers {{ admin_users | map( attribute = 'name' ) | join( ' ' ) }}"
    state: present
  notify: restart ssh