- name: Create Terraform destination directory
  file:
    path: "{{ tf_bin_dir }}"
    state: directory
  
- name: >-
    Download Terraform and unpack exe to {{ tf_bin_dir }}
  unarchive:
    src: >-
      https://releases.hashicorp.com/terraform/{{ tf_version }}/terraform_{{ tf_version }}_darwin_amd64.zip
    dest: "{{ tf_bin_dir }}"
    remote_src: true
