- include_tasks: >-
    {{  lookup(
          'nansi.util.os_tasks',
          (role_path, 'tasks/os') | nansi.util.to_path ) }}

- when: pg_local_admin_users is not none and pg_local_admin_users != ""
  include_tasks: >-
    {{ (role_path, 'tasks/admin_users.yaml') | nansi.util.to_path }}
