- include_tasks: >-
    {{ lookup('nansi.util.os_tasks', role_path + '/tasks/os' ) }}

- when: pyenv_versions is not none
  name: Manage installed versions
  nansi.pyenv.manage_versions:
    versions: "{{ pyenv_versions }}"