- name: Upgrade APT to the latest packages
  apt:
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
    upgrade: safe

- name: See if a reboot is needed
  stat:
    path: /var/run/reboot-required
  register: reboot_required_rsp
  
- when: reboot_required_rsp.stat.exists
  name: Reboot (after APT upgrades & installs)
  reboot:
    reboot_timeout: "{{ reboot_timeout }}"
