- name: >-
    Add user lfs-test-server run will install and run as
  user:
    name: "{{ lfs_test_server_user }}"
    create_home: true
    shell: /bin/bash

# https://github.com/git-lfs/lfs-test-server#installing
- name: >-
    Install lfs-test-server via `go get`
  become: true
  become_user: "{{ lfs_test_server_user }}"
  command:
    cmd: >-
      {{ go_exe_path }} get github.com/github/lfs-test-server
    chdir: "/home/{{ lfs_test_server_user }}"
    creates: "/home/{{ lfs_test_server_user }}/go/bin/lfs-test-server"
