# https://ourcodeworld.com/articles/read/1175/how-to-create-and-configure-your-own-stun-turn-server-with-coturn-in-ubuntu-18-04

# - name: >-
#     Manage {{ 'coturn'|f }} via apt
#   apt:
#     name: coturn
#     state: "{{ coturn_state }}"
#     update_cache: true
#     cache_valid_time: "{{ apt_cache_valid_time }}"

# - name: >-
#     Enable coTURN's TURN server
#   lineinfile:
#     path: "{{ coturn_config_path }}"
#     regexp: '^\s*#\s*TURNSERVER_ENABLED='
#     line: TURNSERVER_ENABLED=1

- name: >-
    Template config file
  template:
    src: "{{ role_path }}/templates/turnserver.conf"
    dest: "{{ coturn_turnserver_conf_path }}"
    backup: yes
  notify: coturn_restart
