wg_cfg_name: wg0

wg_srv_enabled: true

wg_srv_state: >-
  {{
    wg_srv_enabled
    | ternary(
        'started',
        'stopped'
      )
  }}

wg_srv_listen_port: null
wg_srv_allow_to_ip: any
wg_srv_allow_from_ip: any
