- loop: "{{ humans_users }}"
  loop_control:
    loop_var: _user
  name: >-
    Add ssh keys for admin {{ _admin.name }} to all non-admin accounts
  # so that admins can log in *directly* as those users, which allows 
  # managing their systemd user-level services (doesn't work using 
  # `sudo su -`)
  authorized_key:
    user: "{{ _user.name }}"
    key: "https://github.com/{{ _admin.github }}.keys"
    state: present
    exclusive: false
