- with_dict: "{{ user.git }}"
  name: >-
    Configure git for {{ user.name }}
  become: true
  become_user: "{{ user.name }}"
  git_config:
    scope: global
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: "{{ item.value is none | ternary( 'absent', 'present') }}"
  
- when: >-
    'github' in user
  name: >-
    Configure GitHub https username for {{ user.name }}
  become: true
  become_user: "{{ user.name }}"
  git_config:
    scope: global
    name: "credential.https://github.com.username"
    value: "{{ user.github }}"
