coturn_state: present

coturn_config_paths_os_map:
  distribution:
    ubuntu: /etc/default/coturn

coturn_config_path: "{{ lookup('os_dig', coturn_config_paths_os_map) }}"

coturn_server_name: "{{ inventory_hostname }}"
coturn_realm: "{{ coturn_server_name }}"

coturn_turnserver_conf_path_os_map:
  distribution:
    ubuntu: /etc/turnserver.conf

coturn_turnserver_conf_path: >-
  {{ lookup('os_dig', coturn_turnserver_conf_path_os_map) }}

coturn_port: 3478
coturn_tls_port: 5349
