- name: >-
    Manage wg-quick@{{ wg_cfg_name }} service
  service:
    name: "wg-quick@{{ wg_cfg_name }}"
    enabled: "{{ wg_srv_enabled }}"
    state: "{{ wg_srv_state }}"

- when: wg_srv_listen_port | bool
  name: Manage Wireguard listen port
  ufw:
    rule: allow
    port: "{{ wg_if_listen_port | string }}"
    proto: udp
    to_ip: "{{ wg_srv_allow_to_ip }}"
    from_ip: "{{ wg_srv_allow_from_ip }}"
    delete: "{{ wg_srv_state == 'stopped' }}"
    
# https://gist.github.com/kimus/9315140
- name: >-
    Manage packet forwarding in UFW sysctl.conf
  loop:
    - net/ipv4/ip_forward=1
    - net/ipv6/conf/default/forwarding=1
    - net/ipv6/conf/all/forwarding=1
  lineinfile:
    dest: /etc/ufw/sysctl.conf
    line: "{{ (wg_srv_state == 'stopped') | ternary('#', '') }}{{ item }}"
    regexp: >-
      [\\#\s]*{{ item }}
    create: true
  notify:
    - restart_ufw
