# See:
# 
# 1.  https://about.gitlab.com/install/#ubuntu
# 2.  https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh
# 

- name: Install GitLab dependency packages
  apt:
    pkg:
      - curl
      - gnupg
      - debian-archive-keyring
      - apt-transport-https
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Add GitLab GPG key to apt
  apt_key:
    url: "{{ gitlab_gpg_key_url }}"

- name: Add GitLab apt repos
  get_url:
    url: "{{ gitlab_apt_config_url }}"
    dest: "{{ gitlab_apt_source_path }}"
  register: gitlab_installed_apt_repos

# WARNING! This shit is like 2G?!??!
- name: Install `gitlab-ee` via apt ("Omnibus" install)
  apt:
    pkg: gitlab-ee
    update_cache: "{{ gitlab_installed_apt_repos.changed }}"

- name: Copy gitlab.rb (Omnibus config file)
  when: gitlab_config_src is not none
  copy:
    src: "{{ gitlab_config_src }}"
    dest: "{{ gitlab_config_dest }}"
  notify: gitlab_reconfigure_restart
