- name: Fetch peer conf for file for ghetto dist
  fetch:
    src: "{{ _wg_cfg_cc_src }}"
    dest: "{{ _wg_cfg_cc_dest }}"
    mode: '0600'
    flat: true

# - name: Distribute file via Keybase
#   when: >-
#     _wg_cfg_cc_owner is not none
#     and admins is defined
#     and admins | find_by(name=_wg_cfg_cc_owner)
#     and 'keybase' in (admins | find_by(name=_wg_cfg_cc_owner))
#   become: false
#   local_action:
#     module: command
#     argv:
#       - /usr/local/bin/keybase
#       - chat
#       - upload
#       - --title
#       - >-
#           {{ _wg_cfg_cc_name }} -> {{ wg_cfg_hostname }}
#           (Wireguard client config)
#       - --private
#       - "{{ (admins | find_has_all(name=_wg_cfg_cc_owner))['keybase'] }}"
#       - "{{ _wg_cfg_cc_dest }}"
