- name: Add `universal` APT repo
  apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
    - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"
    
- name: Install icecast2 package
  apt:
    name: icecast2
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Enable the daemon
  lineinfile:
    dest: /etc/default/icecast2
    state: present
    regexp: '^ENABLE='
    line: 'ENABLE=true'

- name: Copy icecast.xml config
  template:
    src: icecast.xml
    dest: /etc/icecast2/icecast.xml
  notify: restart icecast2

- name: Enable and start icecast2
  service:
    name: icecast2
    enabled: true
    state: started

- name: Open port 8000
  ufw:
    rule: allow
    port: '8000'
