# Default location for system (as root) installs, since `/root` is generally not 
# world-readable.
pyenv_system_root: /opt/pyenv

# Usual spot for users
pyenv_user_root: "{{ ansible_facts.env.HOME }}/.pyenv"

# Where to "install" pyenv (really, just where to clone the git repo).
# 
# Default depends on if this is a system install (as root) or user,
# see above.
# 
pyenv_root: >-
  {{  (ansible_facts.env.USER == 'root')
      | ternary(pyenv_system_root,  pyenv_user_root) }}

# Define to manage installed versions.
# 
# Must be `null` (don't manage versions) or a `sequence`.
# 
# Each item in the sequence must be on of:
# 
# 1. A `string` version that must be installed.
# 2. A `map` with:
#   1.  A required `version:` key and `string` value defining the version to be
#       managed.
#   2.  An optional `state:` key that's value may be 'present' or 'absent'.
#       If missing, defaults to 'present'. 
# 
pyenv_versions: null
  
pyenv_update: false
